#! /bin/sh
# /etc/init.d/raspberry-wifi-conf

### BEGIN INIT INFO
# Provides:          raspberry-wifi-conf
# Required-Start:    $local_fs $syslog $network
# Required-Stop:     $local_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Script to ensure wifi connectivity
# Description:       A NodeJS application to ensure Wifi connectivity by setting the RPI as an AP if needed
### END INIT INFO

# Add path to node
PATH=/usr/local/bin/node:$PATH

tool_path="/raspberry-wifi-conf"
server_pid="/raspberry-wifi-conf/node.pid"

# Carry out specific functions when asked to by the system
case "$1" in

    start)
        if [ ! -f $server_pid ]; then
            echo "Starting raspberry-wifi-conf service"
            cd $tool_path
            sudo node server.js &
            echo $! > node.pid
        else
            echo "Server is already running. PID is $server_pid"
        fi
        ;;

    stop)
        server_pid=/raspberry-wifi-conf/node.pid
        if [ -f $server_pid ]; then
            sudo kill -9 $(cat $server_pid)
            sudo kill -9 $(($(cat $server_pid) + 1))
            sudo rm $server_pid
            #sudo killall node # lheck workaround
        fi
        ;;

    status)
        if [ -f $server_pid ]; then
            echo "PID: $server_pid"
            ps aux | grep $server_pid
        fi
        ;;

    *)
        echo "Usage: /etc/init.d/raspberry-wifi-conf {start|stop|status}"
        exit 1
        ;;
esac

exit 0
